### PR TITLE
Update cpp20

### PR DESCRIPTION
**Pull request by nilbeleth**
It is necessary to provide similiar updates for Relaxed KDTree class as it was done in previous [patch](https://github.com/sbougerel/spatial/commit/037a01fa3ca1380a53507284bc238eb9773137f5).

### CODE REVIEW

**Comment by nilbeleth** [comment]
Wrong repo

**Comment by sbougerel** [comment]
Hi @nilbeleth, I see you mentioned wrong repo for some reason, but it's actually the correct one. I'm not actively maintaining the library anymore. If you prefer to fork it and host its updates, I'll happily add an explanation in the documentation.

**Comment by nilbeleth** [comment]
Hi, I'm sorry I meant to do this update to a clone of mine 
(https://github.com/Roboauto/spatial) not into the original one. However 
this only for updates of mine and my associates and I certainly wouldn't 
say it is maintained for general usage.

I'm sorry for the misleading comment there.

**Comment by sbougerel** [comment]
No worries. I'm always happy to see the code was useful to others.

**Pull request closed without merging**
